# Generated by Django 4.2.7 on 2023-11-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_airport_latitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='average_fuel_consumption',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
